version: "3.9"

services:
  db:
    image: postgres:16
    container_name: docai-postgres
    environment:
      POSTGRES_DB: docai
      POSTGRES_USER: docai
      POSTGRES_PASSWORD: docai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docai"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: docai-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MH_STORAGE: memory

volumes:
  pgdata:
    driver: local
